// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.6.1
// source: registros.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mensaje struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comando      int32  `protobuf:"varint,1,opt,name=comando,proto3" json:"comando,omitempty"`
	NombreSector string `protobuf:"bytes,2,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase   string `protobuf:"bytes,3,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
	// Types that are assignable to Opcional:
	//
	//	*Mensaje_Valor
	//	*Mensaje_NuevoNombre
	Opcional isMensaje_Opcional `protobuf_oneof:"opcional"`
}

func (x *Mensaje) Reset() {
	*x = Mensaje{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registros_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mensaje) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mensaje) ProtoMessage() {}

func (x *Mensaje) ProtoReflect() protoreflect.Message {
	mi := &file_registros_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mensaje.ProtoReflect.Descriptor instead.
func (*Mensaje) Descriptor() ([]byte, []int) {
	return file_registros_proto_rawDescGZIP(), []int{0}
}

func (x *Mensaje) GetComando() int32 {
	if x != nil {
		return x.Comando
	}
	return 0
}

func (x *Mensaje) GetNombreSector() string {
	if x != nil {
		return x.NombreSector
	}
	return ""
}

func (x *Mensaje) GetNombreBase() string {
	if x != nil {
		return x.NombreBase
	}
	return ""
}

func (m *Mensaje) GetOpcional() isMensaje_Opcional {
	if m != nil {
		return m.Opcional
	}
	return nil
}

func (x *Mensaje) GetValor() int32 {
	if x, ok := x.GetOpcional().(*Mensaje_Valor); ok {
		return x.Valor
	}
	return 0
}

func (x *Mensaje) GetNuevoNombre() string {
	if x, ok := x.GetOpcional().(*Mensaje_NuevoNombre); ok {
		return x.NuevoNombre
	}
	return ""
}

type isMensaje_Opcional interface {
	isMensaje_Opcional()
}

type Mensaje_Valor struct {
	Valor int32 `protobuf:"varint,4,opt,name=valor,proto3,oneof"`
}

type Mensaje_NuevoNombre struct {
	NuevoNombre string `protobuf:"bytes,5,opt,name=nuevo_nombre,json=nuevoNombre,proto3,oneof"`
}

func (*Mensaje_Valor) isMensaje_Opcional() {}

func (*Mensaje_NuevoNombre) isMensaje_Opcional() {}

type Respuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Opciones:
	//
	//	*Respuesta_Direccion
	//	*Respuesta_Vector
	//	*Respuesta_DetalleConLista
	Opciones isRespuesta_Opciones `protobuf_oneof:"opciones"`
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registros_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_registros_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_registros_proto_rawDescGZIP(), []int{1}
}

func (m *Respuesta) GetOpciones() isRespuesta_Opciones {
	if m != nil {
		return m.Opciones
	}
	return nil
}

func (x *Respuesta) GetDireccion() string {
	if x, ok := x.GetOpciones().(*Respuesta_Direccion); ok {
		return x.Direccion
	}
	return ""
}

func (x *Respuesta) GetVector() *Vector {
	if x, ok := x.GetOpciones().(*Respuesta_Vector); ok {
		return x.Vector
	}
	return nil
}

func (x *Respuesta) GetDetalleConLista() *Res_Kais {
	if x, ok := x.GetOpciones().(*Respuesta_DetalleConLista); ok {
		return x.DetalleConLista
	}
	return nil
}

type isRespuesta_Opciones interface {
	isRespuesta_Opciones()
}

type Respuesta_Direccion struct {
	Direccion string `protobuf:"bytes,1,opt,name=direccion,proto3,oneof"`
}

type Respuesta_Vector struct {
	Vector *Vector `protobuf:"bytes,2,opt,name=vector,proto3,oneof"`
}

type Respuesta_DetalleConLista struct {
	DetalleConLista *Res_Kais `protobuf:"bytes,3,opt,name=detalle_con_lista,json=detalleConLista,proto3,oneof"`
}

func (*Respuesta_Direccion) isRespuesta_Opciones() {}

func (*Respuesta_Vector) isRespuesta_Opciones() {}

func (*Respuesta_DetalleConLista) isRespuesta_Opciones() {}

type Vector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vector []int32 `protobuf:"varint,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
}

func (x *Vector) Reset() {
	*x = Vector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registros_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_registros_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_registros_proto_rawDescGZIP(), []int{2}
}

func (x *Vector) GetVector() []int32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type Res_Kais struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombreSector string  `protobuf:"bytes,1,opt,name=nombre_sector,json=nombreSector,proto3" json:"nombre_sector,omitempty"`
	NombreBase   string  `protobuf:"bytes,2,opt,name=nombre_base,json=nombreBase,proto3" json:"nombre_base,omitempty"`
	Valor        int32   `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Vector       []int32 `protobuf:"varint,4,rep,packed,name=vector,proto3" json:"vector,omitempty"`
}

func (x *Res_Kais) Reset() {
	*x = Res_Kais{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registros_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res_Kais) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res_Kais) ProtoMessage() {}

func (x *Res_Kais) ProtoReflect() protoreflect.Message {
	mi := &file_registros_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res_Kais.ProtoReflect.Descriptor instead.
func (*Res_Kais) Descriptor() ([]byte, []int) {
	return file_registros_proto_rawDescGZIP(), []int{3}
}

func (x *Res_Kais) GetNombreSector() string {
	if x != nil {
		return x.NombreSector
	}
	return ""
}

func (x *Res_Kais) GetNombreBase() string {
	if x != nil {
		return x.NombreBase
	}
	return ""
}

func (x *Res_Kais) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Res_Kais) GetVector() []int32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

var File_registros_proto protoreflect.FileDescriptor

var file_registros_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb2, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x61, 0x6e, 0x64, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0b,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x23, 0x0a, 0x0c, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x5f, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x6e,
	0x75, 0x65, 0x76, 0x6f, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70,
	0x63, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x22, 0x93, 0x01, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x63, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x63, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x00, 0x52,
	0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x11, 0x64, 0x65, 0x74, 0x61, 0x6c,
	0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x52, 0x65, 0x73, 0x5f, 0x4b, 0x61, 0x69, 0x73, 0x48, 0x00, 0x52,
	0x0f, 0x64, 0x65, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x61,
	0x42, 0x0a, 0x0a, 0x08, 0x6f, 0x70, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x22, 0x20, 0x0a, 0x06,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x7e,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x5f, 0x4b, 0x61, 0x69, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12,
	0x1f, 0x0a, 0x0b, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x42, 0x61, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x38,
	0x0a, 0x0e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x75, 0x64, 0x5f, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x26, 0x0a, 0x0e, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x5f, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x08, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x1a, 0x0a, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_registros_proto_rawDescOnce sync.Once
	file_registros_proto_rawDescData = file_registros_proto_rawDesc
)

func file_registros_proto_rawDescGZIP() []byte {
	file_registros_proto_rawDescOnce.Do(func() {
		file_registros_proto_rawDescData = protoimpl.X.CompressGZIP(file_registros_proto_rawDescData)
	})
	return file_registros_proto_rawDescData
}

var file_registros_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_registros_proto_goTypes = []interface{}{
	(*Mensaje)(nil),   // 0: Mensaje
	(*Respuesta)(nil), // 1: Respuesta
	(*Vector)(nil),    // 2: Vector
	(*Res_Kais)(nil),  // 3: Res_Kais
}
var file_registros_proto_depIdxs = []int32{
	2, // 0: Respuesta.vector:type_name -> Vector
	3, // 1: Respuesta.detalle_con_lista:type_name -> Res_Kais
	0, // 2: Solicitud_Info.Solicitar_Info:input_type -> Mensaje
	1, // 3: Solicitud_Info.Solicitar_Info:output_type -> Respuesta
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_registros_proto_init() }
func file_registros_proto_init() {
	if File_registros_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_registros_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mensaje); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registros_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Respuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registros_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registros_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res_Kais); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_registros_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Mensaje_Valor)(nil),
		(*Mensaje_NuevoNombre)(nil),
	}
	file_registros_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Respuesta_Direccion)(nil),
		(*Respuesta_Vector)(nil),
		(*Respuesta_DetalleConLista)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_registros_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registros_proto_goTypes,
		DependencyIndexes: file_registros_proto_depIdxs,
		MessageInfos:      file_registros_proto_msgTypes,
	}.Build()
	File_registros_proto = out.File
	file_registros_proto_rawDesc = nil
	file_registros_proto_goTypes = nil
	file_registros_proto_depIdxs = nil
}
